config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'
  resources :line_items do
    put 'decrement', on: :member
    put 'increment', on: :member
  end

end

app/models/cart.rb
# Task D1: Finding a Cart
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  # Task E1 : A Smarter Cart
  def add_product(product_id)
  	current_item = line_items.find_by(product_id: product_id)
  	if current_item
  		current_item.quantity += 1 
  	else
  		current_item = line_items.build(product_id: product_id)
  	end
  	current_item
  end
  # Task E : playing time 1
  def add_product_with_price(product_id,product_price)
  	current_item = line_items.find_by(product_id: product_id)
  	if current_item
  		current_item.quantity += 1
  	else
  		current_item = LineItem.new :product_id => product_id, :price => product_price
  		line_items << current_item
  	end
  	current_item
  end
  # Task E3:
  def total_price
  	line_items.to_a.sum { |item| item.total_price }
  end
  #
  def total_items
    line_items.to_a.sum { |item| item.quantity }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # Task I3: Limit Access
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  # Task E2
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json

  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    # Task E3: Empty cart button
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    # 
    respond_to do |format|
      # format.html { redirect_to store_url, notice: 'Your cart has been emptied!' }
      # Task F4 : Hide empty cart
      format.html { redirect_to store_url }
      # Task F : plying time create a ajax Empty Cart btn
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    # Task E2 : Handle invalid cart id
    def invalid_cart (err)
      logger.error "Attempt to access invalid cart #{params[:id]}"
      ErrorNotifier.error_mailer(err).deliver 
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>

<div class="panel panel-default">
<div class="panel-heading">
<div class="panel-title"><strong>Shopping cart</strong>
</div>
</div>
<div class="panel-body">

<table class="table table-hover">
<thead>
	<th>#</th>
	<th>Book Title</th>
	<th>Price per unit</th>
	<th>Quanity</th>
	<th>Price</th>
	<th></th>
</thead>
<tbody>
<%= render(cart.line_items) %>

<tr class="summary">
<td></td>
<td colspan="2"><b>Total Price</b></td>
<td><%= pluralize cart.total_items , "item" %></td>
<td class="price"><%= number_to_currency(@cart.total_price) %> </td>
<td></td>
</tr>
</tbody>
</table>

<div class="btn-group btn-group-justified">
<% unless current_page?(new_order_path) %>
<%= link_to 'Check out', new_order_path, method: :get , class: "btn btn-primary"%>
<%= link_to 'Empty cart', @cart, method: :delete, data:{ confirm: 'Are you sure?'},class: "btn btn-warning" , remote: true %>
<% end %>

</div>

</div>
</div>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
// Task F: plying time Ajax empty cart btn
// empty Cart function

Helper.emptyCart($('#cart'));

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>
<%= render @cart %>