config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'
  resources :line_items do
    put 'decrement', on: :member
    put 'increment', on: :member
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  # Task D2 :Connecting Product
  has_many :line_items
  # Task G2 : Atom Feeds
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  # Task B1 :Create validation
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01 ,less_than_or_equal_to: 1000}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, uniqueness: true ,format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  # Task C5 :Caching for view/store/index.html.erb
  def self.latest
  	Product.order(:updated_at).last
  end
  # Task D2 :Connecting Product
  private
    def ensure_not_referenced_by_any_line_item
      	if line_items.empty?
      		return true
      	else
      		errors.add(:base, 'Line Items present')
      		return false
      	end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_product
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # Task G2: Atom feeds
  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.xml { render :xml => @product.to_xml(:include => :orders)}
        format.json { render :json => @product.to_json(:include => :orders)}
        format.html
        format.atom
      end
    end
  end
  #
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
    # Task E3: Playing time 3
    def invalid_product
      logger.error "Attempt to access product #{ params[ :id ]}" 
      redirect_to store_url, :notice => 'Invalid product'
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="btn actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="row entry">
 <div class="panel panel-default">
  <div class="panel-body">
   <div class="col-xs-6 col-md-4">
    <%=	 link_to image_tag(product.image_url, class: "img-rounded"), '#', class: "thumbnail" %>
   </div>
	 <div class="col-xs-12 col-md-8">
	  <h3><%= link_to product.title, product %></h3>
	   <%= sanitize(product.description) %>
	    <div class="price_line">
	     <div class="btn-group btn-group-sm">
	     <div class="btn btn-warning btn-sm"><span class="badge price"><%= number_to_currency(product.price) %> </span></div>

	     <%= button_to 'Add to Cart', line_items_path(product_id: product), class: "btn btn-success btn-sm", remote: true %>
	</div>
  </div>
 </div>
</div>
</div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="page-header">
	<h1><strong>Products</strong></h1>
</div>
<% if notice %>
<div id="notice" class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><%= notice %>
  </div>
<% end %>


<% cache ['store', Product.latest] do %>
<% @products.each do |product|%>
<% cache ['row', product] do %>
<%= render product %>
	<% end %>
<% end %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/who_bought.html.erb
<% @product.orders.each do |order| %>
  <h2>Order <%= order.id %></h2>
  <p>Shipped to <%= order.address %></p>
  <table>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Total Price</th>
    </tr>
    <% order.line_items.each do |item| %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency item.total_price %></td>
      </tr>
    <% end %>
    <tr>
      <th colspan="2">total</th>
      <th><%= number_to_currency order.line_items.map(&:total_price).sum %></th>
    </tr>
  </table>
  <p>Paid by <%= order.pay_type %>
<% end %>