config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'
  resources :line_items do
    put 'decrement', on: :member
    put 'increment', on: :member
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>Depot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!-- Task C2: Adding a Page Layout 
	 myTask : Adding bootstrap-sass
-->
<body class='<%= controller.controller_name %>'>
<nav class="navbar nav-pills navbar-fixed-top">
  <div class="container-fluid">
    	 <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
          <% if session[:user_id] %>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

          <% end %>

      </button>
    	 <a class="navbar-brand" href="#">
    	 <%= image_tag("logo.png") %></a>
    	 </div>
       <div class="collapse navbar-collapse"> 
    	 <ul class="nav navbar-nav nav-pills">
        <li class="active"><%= link_to "Browse Products", store_url %></li>
        <li><%= link_to "Price List" %></li>
        <li><%= link_to "Contact Us" %></li>
          <% if session[:user_id] %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <% end %>
          </ul>
          <% if current_page?("/") or current_page?(controller: 'orders', action: 'new') %>          
          <button id="sidecart" type="button" class="btn btn-default navbar-btn">Side cart</button>
          <% end  %>

          <% if session[:user_id] %>
          <ul class="nav nav-pills navbar-nav navbar-right">
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          </ul>
          <% else %>
          <ul class="nav navbar-nav nav-pills navbar-right">
          <li><%= link_to "Sign Up", new_user_url %></li>
          <li><%= link_to "Login", login_url %></li>
          </ul>
          <% end %>
       </div>
  </div>
</nav>
<% if current_page?("/") or current_page?(controller: 'orders', action: 'new')%>
<% if @cart %>
<div id="wrapper" <%if @cart.line_items.empty? %>
class="toggled"
<% end  %>
>
<% else %>
<div id="wrapper">
<% end %>
<% end %>
        <!-- Sidebar -->
        <!-- <div class="container-fluid"> -->
<% if current_page?("/") or current_page?(controller: 'orders', action: 'new')%>

        <div id="sidebar-wrapper">
        <% if @cart %>
        <div id="cart">
        <%= render @cart %> 
        <% end %> 
        </div>
        </div>
        <% end %>
<% if current_page?("/") or current_page?(controller: 'orders', action: 'new')%>

<div id="page-content-wrapper" class="container-fluid">
<% else %>
<div id="page-content-wrapper" class="container">
<div class="col-md-6 col-md-offset-3">
<% end %>

<% if notice %>
<div id="notice" class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><%= notice %>
  </div>
<% end %>
<%= yield %>
</div>
<!-- </div> -->

</div>


</body>
<script type="text/javascript">
  $('#sidecart').on('click',function(e) {
      e.defaultPrevented;
      if ($('#cart tr').length == 0) { 
        alert("Empty Cart"); 
      }
      else {
        $("#wrapper").toggleClass("toggled");
      }
});
</script>
</html>